### ISSUE TITLE
App.Version NullReferenceException

### ISSUE THREAD

**Issue by xkrt** [haf/YoLo#1]
Hi, there is a problem with https://github.com/haf/YoLo/blob/master/YoLo.fs#L593, if calling assembly doesnt have that attribute - NRE will be raised even if App.Version static field doesnt used due F#/.NET some optimization.

I spot that issue with https://github.com/SuaveIO/suave/commit/a37f7eae27a645176e0ac466b0eb953f376c5486 by running Example console, build by VS2013 in Release configuration. .NET 4.5, F# runtime 4.3.1.0.

Maybe Value should be `string option` instead of `string`.

**Comment by haf** [comment]
Fixed.
