### ISSUE TITLE
Build problem on windows not on mono

### ISSUE THREAD

**Issue by halcwb** [haf/YoLo#4]
I added your YoLo file to a project of mine, using paket. But build fails on windows but passes on mono. In windows I have to remove the internal module modifier. See: https://ci.appveyor.com/project/halcwb/genunitapp/build/1.0.102 and
https://travis-ci.org/halcwb/GenUnitApp/builds/141458423

**Comment by halcwb** [comment]
I did an pull request which fixed the issue for me. Feel free to reject or accept.

**Comment by haf** [comment]
Why would it fail on mono? Hmmm... Well, let's move on with our lifes.
